### ISSUE TITLE
Epic Implement Room Pattern for all models

### ISSUE THREAD

**Issue by cryptosmithio** [ghostwalkerj/champagneroom-app#76]
- [x] Separate models into frontend and server schemas
- [x] Remove old ZOD schemas use model schemas 
- [x] Change load methods to return forms instead of entities
